#!/usr/bin/env python

import urllib2
import json

url = 'http://localhost:8080/v3/nodes'

r = urllib2.Request(url)
r.add_header('Accept', 'application/json')
u = urllib2.urlopen(r)

print( "%-24s %s %25s" % ( 'Name', 'Facts', 'Report'))
for i in sorted(json.load(u), key = lambda o: o['facts_timestamp']):
    print( "%-24s %s %s" % (
        i['name'],
        i['facts_timestamp'],
        i['report_timestamp'],
        ))
u.close()
