#!/usr/bin/env python
# Licensed under the GPLv2

import urllib2
import json
import sys

if len(sys.argv) > 1:
    fact = sys.argv[1]
else:
    fact = False

debug = False

url = 'http://localhost:8080/v3/nodes'

r = urllib2.Request(url)
r.add_header('Accept', 'application/json')
u = urllib2.urlopen(r)

hosts = list()

for i in sorted(json.load(u), key = lambda o: o['name']):
    fact_url = '%s/%s/facts/%s' % (url, i['name'], fact)
    if debug:
        sys.stderr.write(fact_url + '\n')
    fact_request = urllib2.Request(fact_url)
    fact_request.add_header('Accept', 'application/json')
    fu = urllib2.urlopen(fact_request)
    for j in sorted(json.load(fu), key = lambda o: o['name']):
        print('%s: %s' % (i['name'], j['value']))
    fu.close()
u.close()
